from PyQt5 import QtCore, QtGui, QtWidgets

from Helpers import TopFrame, MenuFrame, get_icon
import time
"""
Class to create the home page of the software.
"""
class PageHome(QtWidgets.QFrame):

    def __init__(self, parent=None):
        start_time = time.time()
        super(QtWidgets.QFrame, self).__init__(parent)
   
        # set frame properties
        self.setFocusPolicy(QtCore.Qt.NoFocus)
        self.setStyleSheet("#btn_leftImg:hover, #btn_rightImg:hover{background-color:transparent;}")
        self.setObjectName("page_home")
        
        # basic layout
        self.verticalLayout = QtWidgets.QVBoxLayout(self)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        
        # create the blue top bar
        self.frame_topBar = TopFrame(":/icons/icons/home_w.png", "frame_homeBar")     
        self.verticalLayout.addWidget(self.frame_topBar)
        
        # create the cotrol bar containing the menu
        #self.frame_controlBar = MenuFrame("Handbook", "frame_controlBar_handbook")  
        #self.verticalLayout.addWidget(self.frame_controlBar)
        
        self.frame_controlBar = QtWidgets.QFrame(self)
        self.frame_controlBar.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_controlBar.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_controlBar.setStyleSheet("")
        self.frame_controlBar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_controlBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_controlBar.setLineWidth(0)
        self.frame_controlBar.setObjectName("frame_controlBar")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_controlBar)
        self.horizontalLayout_4.setContentsMargins(11, 5, 11, 5)
        self.horizontalLayout_4.setSpacing(4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        
        self.btn_menu2 = QtWidgets.QPushButton(self.frame_controlBar)
        self.btn_menu2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_menu2.sizePolicy().hasHeightForWidth())
        self.btn_menu2.setSizePolicy(sizePolicy)
        self.btn_menu2.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_menu2.setMaximumSize(QtCore.QSize(40, 40))
        self.btn_menu2.setText("")
        self.btn_menu2.setIconSize(QtCore.QSize(30, 30))
        self.btn_menu2.setObjectName("btn_menu2")
        self.horizontalLayout_4.addWidget(self.btn_menu2)
        spacerItem2 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.btn_imgSwitch = QtWidgets.QPushButton(self.frame_controlBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_imgSwitch.sizePolicy().hasHeightForWidth())
        self.btn_imgSwitch.setSizePolicy(sizePolicy)
        self.btn_imgSwitch.setMinimumSize(QtCore.QSize(60, 40))
        self.btn_imgSwitch.setMaximumSize(QtCore.QSize(60, 40))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn_imgSwitch.setFont(font)
        self.btn_imgSwitch.setStyleSheet("")
        self.btn_imgSwitch.setObjectName("btn_imgSwitch")
        self.horizontalLayout_4.addWidget(self.btn_imgSwitch)
        self.btn_filter = QtWidgets.QPushButton(self.frame_controlBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_filter.sizePolicy().hasHeightForWidth())
        self.btn_filter.setSizePolicy(sizePolicy)
        self.btn_filter.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_filter.setMaximumSize(QtCore.QSize(40, 40))
        self.btn_filter.setText("")
        
        self.btn_filter.setIcon(get_icon(":/icons/icons/filter.png"))
        #self.btn_filter.setIcon(self.icon_loader.get_icon("icon2"))
        
        
        self.btn_filter.setIconSize(QtCore.QSize(30, 30))
        self.btn_filter.setObjectName("btn_filter")
        self.horizontalLayout_4.addWidget(self.btn_filter)
        self.comboBox_imgRemark = QtWidgets.QComboBox(self.frame_controlBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_imgRemark.sizePolicy().hasHeightForWidth())
        self.comboBox_imgRemark.setSizePolicy(sizePolicy)
        self.comboBox_imgRemark.setMinimumSize(QtCore.QSize(0, 40))
        self.comboBox_imgRemark.setMaximumSize(QtCore.QSize(16777215, 40))
        self.comboBox_imgRemark.setEditable(True)
        self.comboBox_imgRemark.setObjectName("comboBox_imgRemark")
        self.comboBox_imgRemark.addItem("")
        self.comboBox_imgRemark.addItem("")
        self.comboBox_imgRemark.addItem("")
        self.comboBox_imgRemark.addItem("")
        self.comboBox_imgRemark.addItem("")
        self.comboBox_imgRemark.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox_imgRemark)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.btn_zoom = QtWidgets.QPushButton(self.frame_controlBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_zoom.sizePolicy().hasHeightForWidth())
        self.btn_zoom.setSizePolicy(sizePolicy)
        self.btn_zoom.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_zoom.setMaximumSize(QtCore.QSize(40, 40))
        self.btn_zoom.setText("")     
        self.btn_zoom.setIcon(get_icon(":/icons/icons/glass.png"))       
        self.btn_zoom.setIconSize(QtCore.QSize(30, 30))
        self.btn_zoom.setObjectName("btn_zoom")
        self.horizontalLayout_4.addWidget(self.btn_zoom)
        self.btn_add = QtWidgets.QPushButton(self.frame_controlBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_add.sizePolicy().hasHeightForWidth())
        self.btn_add.setSizePolicy(sizePolicy)
        self.btn_add.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_add.setMaximumSize(QtCore.QSize(40, 40))
        self.btn_add.setText("")
        self.btn_add.setIcon(get_icon(":/icons/icons/plus.png"))
        self.btn_add.setIconSize(QtCore.QSize(30, 30))
        self.btn_add.setObjectName("btn_add")
        self.horizontalLayout_4.addWidget(self.btn_add)
        self.btn_previous = QtWidgets.QPushButton(self.frame_controlBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_previous.sizePolicy().hasHeightForWidth())
        self.btn_previous.setSizePolicy(sizePolicy)
        self.btn_previous.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_previous.setMaximumSize(QtCore.QSize(40, 40))
        self.btn_previous.setText("")
        self.btn_previous.setIcon(get_icon(":/icons/icons/arrow_left_small.png"))
        self.btn_previous.setIconSize(QtCore.QSize(30, 30))
        self.btn_previous.setObjectName("btn_previous")
        self.horizontalLayout_4.addWidget(self.btn_previous)
        self.btn_placeholder = QtWidgets.QPushButton(self.frame_controlBar)
        self.btn_placeholder.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_placeholder.sizePolicy().hasHeightForWidth())
        self.btn_placeholder.setSizePolicy(sizePolicy)
        self.btn_placeholder.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_placeholder.setMaximumSize(QtCore.QSize(40, 40))
        self.btn_placeholder.setText("")
        self.btn_placeholder.setIconSize(QtCore.QSize(30, 30))
        self.btn_placeholder.setObjectName("btn_placeholder")
        self.horizontalLayout_4.addWidget(self.btn_placeholder)
        self.btn_next = QtWidgets.QPushButton(self.frame_controlBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_next.sizePolicy().hasHeightForWidth())
        self.btn_next.setSizePolicy(sizePolicy)
        self.btn_next.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_next.setMaximumSize(QtCore.QSize(40, 40))
        self.btn_next.setText("")
        self.btn_next.setIcon(get_icon(":/icons/icons/arrow_right_small.png"))
        self.btn_next.setIconSize(QtCore.QSize(30, 30))
        self.btn_next.setObjectName("btn_next")
        self.horizontalLayout_4.addWidget(self.btn_next)
        self.btn_delete = QtWidgets.QPushButton(self.frame_controlBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_delete.sizePolicy().hasHeightForWidth())
        self.btn_delete.setSizePolicy(sizePolicy)
        self.btn_delete.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_delete.setMaximumSize(QtCore.QSize(40, 40))
        self.btn_delete.setText("")
        self.btn_delete.setIcon(get_icon(":/icons/icons/bin_closed.png"))
        self.btn_delete.setIconSize(QtCore.QSize(30, 30))
        self.btn_delete.setObjectName("btn_delete")
        self.horizontalLayout_4.addWidget(self.btn_delete)
        self.btn_undo = QtWidgets.QPushButton(self.frame_controlBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_undo.sizePolicy().hasHeightForWidth())
        self.btn_undo.setSizePolicy(sizePolicy)
        self.btn_undo.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_undo.setMaximumSize(QtCore.QSize(40, 40))
        self.btn_undo.setText("")
        self.btn_undo.setIcon(get_icon(":/icons/icons/undo.png"))
        self.btn_undo.setIconSize(QtCore.QSize(30, 30))
        self.btn_undo.setObjectName("btn_undo")
        self.horizontalLayout_4.addWidget(self.btn_undo)
        spacerItem4 = QtWidgets.QSpacerItem(354, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        spacerItem6 = QtWidgets.QSpacerItem(7, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        
        self.btn_menu = QtWidgets.QPushButton(self.frame_controlBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_menu.sizePolicy().hasHeightForWidth())
        self.btn_menu.setSizePolicy(sizePolicy)
        self.btn_menu.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_menu.setMaximumSize(QtCore.QSize(40, 40))
        self.btn_menu.setText("")
        self.btn_menu.setIcon(get_icon(":/icons/icons/menu.png"))
        self.btn_menu.setIconSize(QtCore.QSize(30, 30))
        self.btn_menu.setObjectName("btn_menu")

        
        self.horizontalLayout_4.addWidget(self.btn_menu)
        self.verticalLayout.addWidget(self.frame_controlBar)
        self.frame_imgDisplay = QtWidgets.QFrame(self)
        self.frame_imgDisplay.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_imgDisplay.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_imgDisplay.setLineWidth(0)
        self.frame_imgDisplay.setObjectName("frame_imgDisplay")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_imgDisplay)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        
        self.frame_left = QtWidgets.QFrame(self.frame_imgDisplay)
        self.frame_left.setMinimumSize(QtCore.QSize(60, 0))
        self.frame_left.setMaximumSize(QtCore.QSize(60, 16777215))
        self.frame_left.setFocusPolicy(QtCore.Qt.NoFocus)
        self.frame_left.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_left.setStyleSheet("")
        self.frame_left.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_left.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left.setObjectName("frame_left")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_left)
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem7)
        
        self.btn_leftImg = QtWidgets.QPushButton(self.frame_left)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_leftImg.sizePolicy().hasHeightForWidth())
        self.btn_leftImg.setSizePolicy(sizePolicy)
        self.btn_leftImg.setText("")
        self.btn_leftImg.setIcon(get_icon(":/icons/icons/arrow_left_big.png"))
        self.btn_leftImg.setIconSize(QtCore.QSize(20, 40))
        self.btn_leftImg.setCheckable(False)
        self.btn_leftImg.setFlat(False)
        self.btn_leftImg.setObjectName("btn_leftImg")
        self.verticalLayout_2.addWidget(self.btn_leftImg)
        
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem8)
        
        self.label_imgCount = QtWidgets.QLabel(self.frame_left)
        self.label_imgCount.setMinimumSize(QtCore.QSize(0, 40))
        self.label_imgCount.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_imgCount.setAlignment(QtCore.Qt.AlignCenter)
        self.label_imgCount.setObjectName("label_imgCount")
        self.verticalLayout_2.addWidget(self.label_imgCount)
        self.horizontalLayout_5.addWidget(self.frame_left)
        self.frame_img = QtWidgets.QFrame(self.frame_imgDisplay)
        self.frame_img.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_img.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_img.setObjectName("frame_img")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_img)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.image = QtWidgets.QLabel(self.frame_img)
        self.image.setText("")
        self.image.setPixmap(QtGui.QPixmap("../data/maritime_dataset_25/training_data_animals/0.jpg"))
        self.image.setScaledContents(True)
        self.image.setAlignment(QtCore.Qt.AlignCenter)
        self.image.setObjectName("image")
        self.gridLayout_2.addWidget(self.image, 0, 0, 1, 1)
        self.horizontalLayout_5.addWidget(self.frame_img)
        self.frame_right = QtWidgets.QFrame(self.frame_imgDisplay)
        self.frame_right.setMinimumSize(QtCore.QSize(60, 0))
        self.frame_right.setMaximumSize(QtCore.QSize(60, 16777215))
        self.frame_right.setStyleSheet("")
        self.frame_right.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_right.setObjectName("frame_right")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_right)
        self.verticalLayout_3.setContentsMargins(5, 5, 5, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem9)
        
        self.btn_rightImg = QtWidgets.QPushButton(self.frame_right)
        self.btn_rightImg.setText("")        
        self.btn_rightImg.setIcon(get_icon(":/icons/icons/arrow_right_big.png"))
        self.btn_rightImg.setIconSize(QtCore.QSize(20, 40))
        self.btn_rightImg.setObjectName("btn_rightImg")
        self.verticalLayout_3.addWidget(self.btn_rightImg)
        
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem10)
        self.btn_openImg = QtWidgets.QPushButton(self.frame_right)
        self.btn_openImg.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_openImg.setMaximumSize(QtCore.QSize(40, 40))
        self.btn_openImg.setText("")
        self.btn_openImg.setIcon(get_icon(":/icons/icons/open_image.png"))
        self.btn_openImg.setIconSize(QtCore.QSize(30, 30))
        self.btn_openImg.setObjectName("btn_openImg")
        self.verticalLayout_3.addWidget(self.btn_openImg)
        self.horizontalLayout_5.addWidget(self.frame_right)
        self.verticalLayout.addWidget(self.frame_imgDisplay)
        
        #print(f"page home init: {time.time() - start_time}")